// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pgstore

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type UserDatum struct {
	ID               uuid.UUID
	Ip               string
	UserAgent        string
	Timestamp        pgtype.Timestamptz
	Location         string
	Device           string
	Action           string
	JsonResponseBody string
	Referrer         string
	RequestMethod    string
	RequestPath      string
}
