name: Build and Deploy GAMA Queue

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Change Grafana default password
        run: sed -i "s/^GAMA_GRAFANA_PASSWORD=.*/GAMA_GRAFANA_PASSWORD=\"${{ secrets.GRAFANA_PASSWORD }}\"/" .env
      - name: Build Docker Image
        run: docker build -t caiogallo2401/go-ama-queue .
      - name: Push Image to Docker Hub
        run: docker push caiogallo2401/go-ama-queue:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST_AWS}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME_AWS}}

          script: |
            cd /var/www/go-ama-queue/
            git checkout main
            git pull origin main
            docker pull caiogallo2401/go-ama-queue:latest
            docker compose down --remove-orphans
            docker compose -f docker-compose.production.yaml build --no-cache
            docker compose -f docker-compose.production.yaml up --build -d
            sleep 15
            docker exec gama-grafana grafana-cli admin reset-admin-password $GAMA_GRAFANA_PASSWORD
            exit

